### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by jamillosantos** [luckas99/mdb#2]
**Briefing**

This one is straight forward. The `i18next` should be initialized for this project and should support English and Portuguese.

The language will be provided from the same URL that the theme information will be pulled (check #1). So, we don't need to detect the browser language.

PS: You probably will not find anything to translate here. So, create some random phrase to be placed somewhere.

**Tasks**
- [ ] Add `i18next` support;
- [ ] Create translation file for Portuguese;
- [ ] Create translation file for English;
- [ ] Create a simple language selector to update the language in runtime;
- [ ] Put a random phrase to demonstrate the translation working;
